# Generated by Django 4.0 on 2023-09-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
