# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies with poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.7.0
        poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root --only test
    - name: Lint with poetry
      run: |
        make app-lint
    - name: Test with pytest
      run: |
        make app-test
